version: 0.2
phases:
  install:
    runtime-versions:
      docker: 20
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region us-east-1 --no-include-email)
      - REPOSITORY_URI=817113695192.dkr.ecr.us-east-1.amazonaws.com
      - ECR=data_pipeline_wms_to_azure
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $REPOSITORY_URI/$ECR:latest .
      - docker tag $REPOSITORY_URI/$ECR:latest $REPOSITORY_URI/$ECR:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI/$ECR:latest
      - docker push $REPOSITORY_URI/$ECR:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $ECR $REPOSITORY_URI/$ECR:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - '**/*'
